a=int(input("enter the a value: "))
b=int(input("enter the b value: "))
print(a+b)
c=int(input("enter the c value: "))
d=int(input("enter the d value: "))
print(c-d)
e=int(input("enter the e value: "))
f=int(input("enter the f value: "))
print(e%f)
